### PR TITLE
Singletons Update

### PR DESCRIPTION
**Pull request by Abstract45**
Added private initializer method for singleton and an alternative method for creating a singleton. Previously you could initialize the class using its default initializer i.e. let x = MyClass() and use its methods.

### CODE REVIEW

**Comment by timvermeulen** [comment]
I much prefer the alternative way that you provided over the original way. It just seems pointless to make a private variable if you don't need to. @iwasrobbed, what do you think?

**Comment by iwasrobbed** [comment]
@miwand @timvermeulen Indeed, the updated way is preferred with `static let` these days, so I'd rather just remove the old way entirely. 

Also @miwand can you please make sure to indent the code examples to keep them looking clean ✨

**Comment by Abstract45** [comment]
Ok will do in the future 👍

**Comment by iwasrobbed** [comment]
Rolled into https://github.com/iwasrobbed/Swift-CheatSheet/commit/ac7293ac2c9c8f4b7193fb571ea168183ba47970

**Pull request closed without merging**
